   name: compile-driver

   on:
     push:
       branches: [ main, gh-actions-test ]
     pull_request:
       branches: [ main, gh-actions-test ]

   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: compile driver
        run: make
    build_fedora:
      runs-on: ubuntu-latest
      container: fedora:latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: compile driver
        run: make
